CREATE PROC PIPING.DeleteISO
@isoId INT
AS

BEGIN TRY
    BEGIN TRANSACTION DELETEISO WITH MARK 'DELETEISO'
        DELETE FROM PIPING.tblWelders WHERE JointId IN (SELECT PIPING.tblWeldingMap.Id FROM PIPING.tblWeldingMap WHERE PIPING.tblWeldingMap.ISOId = @isoId)
        DELETE FROM PIPING.tblWeldingMap WHERE PIPING.tblWeldingMap.ISOId = @isoId
        DELETE FROM PIPING.tblIsos WHERE isoID = @isoId
    COMMIT TRANSACTION DELETEISO
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION DELETEISO
END CATCH
